disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace

opt_in_rules:
  - empty_count

excluded:
  - Carthage
  - Pods

force_cast: warning

force_try:
  severity: warning

line_length: 300

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone

identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"

identifier_name:
    allowed_symbols: "_"
    min_length: 2
    max_length:
        warning: 90
        error: 1000
    excluded:
        - id
