# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
      verbose: true
      )
  end

  desc "Push a new beta build to Fabric"
  lane :adhoc do
    setup_travis
    increment_build_number
    update_info_plist

    clean_build_artifacts

    match(
      type: "adhoc",
      app_identifier: "com.siriuscode.synchronoss",
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      readonly: true,
      verbose: true,
      clone_branch_directly: true,
      force_for_new_devices: true
      )

    gym
    send_crashlytics
  end

  desc "Runs all the tests"
  lane :test do
    scan(device: "iPhone 6s")
  end

  desc "Send to Crashlytics"
  private_lane :send_crashlytics do

    crashlytics(
      api_token: "98172dd97f0390bc2912872b57613dbb1be6cb34",
      build_secret: "b8ab2b0b7b0821f6ed7d72ac78d1df563f3c8d6a4c90843533ff87fd5f6f465d",
      ipa_path: "./fastlane/Build/Synchronoss.ipa",
      groups: "fastlane",
      notes: "New version of Synchronoss.",
      notifications: true
      )

  end

  after_all do |lane|

    delete_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"]
      )

    slack(
      message: "New version of Synchronoss."
      )
  end

  error do |lane, exception|
    delete_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"]
      )
      slack(
        message: exception.message,
        success: false
        )
    end
end
